name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          body: |
            ## CodeGraph ${{ github.ref_name }}
            
            ### Installation
            
            #### Quick Install (Recommended)
            ```bash
            curl -fsSL https://raw.githubusercontent.com/lucasmuzynoski/CodeGraph/master/install.sh | bash
            ```
            
            #### Manual Download
            Download the appropriate binary for your platform below.
            
            ### What's New
            - Zero-configuration setup - just install and go!
            - Auto-indexing on first use
            - Auto-refresh to keep index updated
            - New 'mcp' command for simplified usage
            - Environment variable support for project paths
          draft: false
          prerelease: false

  build-release:
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest  
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v4
      
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: codegraph
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ matrix.target }}
          archive: $bin-$target